### ISSUE TITLE
Add button to set numerical parameters

### ISSUE THREAD

**Issue by Alondruck** [teamspatzenhirn/rig_reconfigure#25]
Each time you type something in the text box it automatically executes the function to set the parameter. To avoid inconveniences it would be better to have a button that executes this function to set all the parameters.

Apparently, this behavior happens with numerical parameters only (int and double). With string parameters, you have to press enter in the text box to set the parameter, which is fine.

**Comment by ottojo** [comment]
This behavior was recently adjusted for string parameters in #18. It seems useful to have the same behavior for numbers as well.

ping @authaldo

**Comment by authaldo** [comment]
Should be fixed in #27
